### ISSUE TITLE
Installer: Add ansible_host to LXD containers in inventory

### ISSUE THREAD

**Issue by cmxela** [cmxela/thinkube#53]
## Problem

The installer generates an inconsistent inventory structure where:
- Baremetal hosts have `ansible_host` defined (e.g., bcn1 has `ansible_host: "192.168.1.101"`)
- LXD containers only have `lan_ip` defined but are missing `ansible_host` (e.g., vm-2 has `lan_ip: "192.168.1.112"` but no `ansible_host`)

This inconsistency makes it difficult to write generic Ansible templates that work for both baremetal hosts and LXD containers.

## Current Behavior

LXD containers in the inventory look like:
```yaml
vm-2:
  parent_host: "bcn1"
  memory: "48GB"
  cpu_cores: 12
  disk_size: "500GB"
  arch: "x86_64"
  lan_ip: "192.168.1.112"
  internal_ip: "192.168.100.11"
  zerotier_ip: "192.168.191.12"
  zerotier_enabled: true
  gpu_passthrough: true
  pci_slot: "0000:01:00.0"
```

## Expected Behavior

LXD containers should include `ansible_host` like baremetal hosts:
```yaml
vm-2:
  ansible_host: "192.168.1.112"  # <-- This should be added
  parent_host: "bcn1"
  memory: "48GB"
  cpu_cores: 12
  disk_size: "500GB"
  arch: "x86_64"
  lan_ip: "192.168.1.112"
  internal_ip: "192.168.100.11"
  zerotier_ip: "192.168.191.12"
  zerotier_enabled: true
  gpu_passthrough: true
  pci_slot: "0000:01:00.0"
```

## Impact

This affects any playbook that tries to use `{{ hostvars[host]['ansible_host'] }}` in templates, as it works for baremetal hosts but fails for LXD containers.

## Suggested Fix

When generating the inventory for LXD containers, add:
```yaml
ansible_host: "{{ lan_ip }}"
```

This ensures consistency across all host types in the inventory.
